kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: j4kdemo
  namespace: {{ $.Release.Namespace }}
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/disable_cookies: 'true'
spec:
  host: ''
  to:
    kind: Service
    name: j4kdemo
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None